name: '${name}'
version: '${version}'
main: org.finetree.fineharvest.FineHarvest
api-version: '1.21'
folia-supported: true
authors: [ Steampunk_Sam ]
description: Allows auto-plant harvesting with Hoes
website: finetree.org
softdepend: [ mcMMO, AureliumSkills, GriefPrevention, Lands, WorldGuard, Towny, ProtectionStones, PlotSquared, GriefDefender, EssentialsAntiBuild, Essentials ]
permissions:
  fineharvest.use:
    description: Allows use of FineHarvest
    default: op